### ISSUE TITLE
Not updated on flows.nodered.org

### ISSUE THREAD

**Issue by Akeboshiwind** [tomgidden/node-red-contrib-timed-counter#11]
Hi, as you can see here: https://flows.nodered.org/node/node-red-contrib-timed-counter
The latest version the flow library has is 0.0.4, whereas the latest version here is 0.0.5.

I did a bit of digging and found this: https://nodered.org/docs/creating-nodes/packaging, at the bottom under `Adding to flows.nodered.org`. It looks like you either need to request a refresh or add the node manually.

I'd be grateful if you could do that :)

**Comment by tomgidden** [comment]
Done... better late than never :)

Thanks

**Comment by Akeboshiwind** [comment]
🙏
