### ISSUE TITLE
Request: Send once count is reached

### ISSUE THREAD

**Issue by PaulWieland** [tomgidden/node-red-contrib-timed-counter#12]
I would like to use the timed counter node to count the number of times a switch is pressed. If pressed 3x within 3 seconds, then perform some action. The problem is that the node always waits 3 seconds before returning.

It would be really useful if you could configure the count that the node would return on.

This could also be done so that the node doesn't return unless the count is reached within the designated timeout.

**Comment by tomgidden** [comment]
@PaulWieland Good idea, although with the name "timed-counter" it might be a bit of feature creep!

I've added this and pushed version 0.1.0; it's not rigorously tested, but it seems okay to me.

There's some extra clean-up there too.

Please let me know how you get on with it.
