### ISSUE TITLE
RFE - add Time increment (i.e. minutes, seconds, hours) - code attached

### ISSUE THREAD

**Issue by juggledad** [tomgidden/node-red-contrib-timed-counter#2]
I really like this node but wanted to use it with minutes instead of milliseconds. It is just easier to add 3 minutes than figure that each minute is 60,000 miliseconds so 3*60000=180000 and enter 180,000.

I added  a 'increment' field to the html where you can pick Milliseconds, Seconds, Minutes or Hours where:
Milliseconds = 1
Seconds=1000
Minutes=60000
Hours=3600000
and in the js, multiply the time value by the increment.

[timed-counter html.txt](https://github.com/tomgidden/node-red-contrib-timed-counter/files/1866260/timed-counter.html.txt)
[timed-counter js.txt](https://github.com/tomgidden/node-red-contrib-timed-counter/files/1866261/timed-counter.js.txt)

**Comment by tomgidden** [comment]
Hi!

Sorry for my lateness for this.  I've implemented this in 5687b07932ae9b0de792dfb4aa8f7b38c156d735

Thanks for the suggestion!
