### ISSUE TITLE
Feature request: counting on a per-topic basis

### ISSUE THREAD

**Issue by drmibell** [tomgidden/node-red-contrib-timed-counter#4]
A recent discussion on the node-RED forum (https://discourse.nodered.org/t/send-payload-when-certain-event-is-received-x-number-of-times-within-specified-timeframe/5460) has suggested that it would be useful for your node to count events separately for each `msg.topic`. I posted a flow there with a `function` node showing how it could be done. I hope you will consider adding this feature.

**Comment by tomgidden** [comment]
Hi!

Sorry for the delay on answering this.  It was easier said than done, but I've refactored the code to allow multiple handlers and used that to implement it.  Hopefully it'll work as expected.

Thanks for the suggestion!

Tom
