### ISSUE TITLE
How can i remove this from debug ? 

### ISSUE THREAD

**Issue by MattL0** [tomgidden/node-red-contrib-timed-counter#5]
Every time node-red is deployed, I get theses in debugs .

is there a way to emove this ? thanks 

![Capture](https://user-images.githubusercontent.com/27497561/92336229-6f243700-f06c-11ea-8998-725619c71861.PNG)

**Comment by juggledad** [comment]
What kind of deploy do you do? a 'Full", "Modified Flows" or 'Modified Nodes"?

**Comment by MattL0** [comment]
Thank for replying . I have been able to remove the code from source on this. 

To answer the question this is appearing at every type of deploy.

**Comment by juggledad** [comment]
Feel like showing what code you removed in case someone else runs into this?

**Comment by medianodehome** [comment]
@juggledad 
From source file: `/node-red/node_modules/node-red-contrib-timed-counter/timed-counter.js`
Comment out Line #123:
`node.warn("Creating handler for "+topic);`

Edit: Don't forget to restart Node-Red after making this change.

**Comment by MattL0** [comment]
> Feel like showing what code you removed in case someone else runs into this?
i am so sorry. I completly forgot to reply

**Comment by tomgidden** [comment]
Sorry, I missed this.  I'll remove this debug message;  I haven't looked at this code in a while, but I'm fairly sure it's unnecessary.

**Comment by MattL0** [comment]
Thanks :)
