### ISSUE TITLE
Log Entry [warn] "Creating handler for all"

### ISSUE THREAD

**Issue by djiwondee** [tomgidden/node-red-contrib-timed-counter#7]
There is an output from this node-red-contrib in the node-red-log:

`24 Nov 08:19:01 - [warn] [timed-counter:click counter] Creating handler for all`

What does this mean? It seems to appear just one time (init?) and can probably ignored.

**Comment by tomgidden** [comment]
Yes, I think that's just excess debugging left in there.  I've removed it.  Thanks!

**Comment by ghost** [comment]
Sorry to comment on an old issue, but I would like to bring to your attention that this change has not been published to npm.. so the node.warn is still in there when installing from the palette.

Thanks for the package, still the only one I could find that only send the last message received in a time interval.

**Comment by tomgidden** [comment]
@renzo-s Thanks for pointing out that oversight!  0.0.5 should be up on NPM now.
