### ISSUE TITLE
Great node, thanks What is fixedtimeout for?

### ISSUE THREAD

**Issue by frownbreaker** [tomgidden/node-red-contrib-timed-counter#9]
What is the fixedtimeout option for?

**Comment by tomgidden** [comment]
Sorry for the (year long) delay in answering!

Normally, if this node gets another message within the time limit, it'll reset the timer, and so the next message, and so on... that way, it'll only report when it _stops_ getting messages.

With Fixed Timeout it has a limited period to count the messages and won't reset.

So, if the timeout is set to 30 seconds and a message is sent every 10 seconds forever, then normally it'll keep counting forever as each message resets the clock.  

If you set 'fixedTimeout' it'll report "3" after 30 seconds, then start counting again with the next one.
